services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    networks:
      - internal
    
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - server
    networks:
      - internal

networks:
  internal:
    driver: bridge